"""new fields in user model

Revision ID: 25994d245d29
Revises: a24dc2a86364
Create Date: 2026-01-03 23:31:43.309267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25994d245d29'
down_revision = 'a24dc2a86364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
